export const ChartType = {
  APPOINTMENT: 'APPOINTMENT',
  REGISTRATION: 'REGISTRATION',
  CONSULTING: 'CONSULTING',
  TREATMENT: 'TREATMENT',
  SURGERY: 'SURGERY',
  SKINCARE: 'SKINCARE',
  NURSE_OPERATION: 'NURSE_OPERATION',
  NURSE_CARE: 'NURSE_CARE',
  PAYMENT: 'PAYMENT',
};
